export const keywords = [
  // PALAVRAS-CHAVE FOCO: REVIEWS E COMPRAS
  'melhor custo benefício',
  'review de produtos',
  'comparativo de produtos',
  'guia de compras',
  'dicas de compra',
  'produtos para comprar',
  'compras online',
  'melhores ofertas',
  'promoções',
  'link de afiliado',
  'amazon afiliados',
  'mercado livre',
  'vale a pena comprar',

  // CATEGORIAS DIVERSAS (NOVO FOCO)
  'eletrônicos',
  'eletrodomésticos',
  'produtos para casa',
  'decoração',
  'utensílios de cozinha',
  'saúde e beleza',
  'ferramentas',
  'esporte e lazer',
  'produtos infantis',
  'pets',

  // PALAVRAS-CHAVE TECH (MANTIDAS PELA RELEVÂNCIA)
  'notebooks',
  'smartphones',
  'acessórios tech',
  'wearables',
  'mouse gamer',
  'teclado mecânico',
  'fones bluetooth',
  'PC gamer',
  'hardware',
  'gadgets',
  'tecnologia para o dia a dia',
  'dispositivos inteligentes',
  'melhores notebooks',
  'melhores celulares',
]