export const keywords = [
    'tecnologia',
    'blog de tecnologia',
    'posts de tecnologia',
    'artigos de tecnologia',
    'notícias de tecnologia',
    'inovação',
    'inteligência artificial',
    'IA',
    'machine learning',
    'chatGPT',
    'openAI',
    'futuro da tecnologia',
    'programação',
    'desenvolvimento web',
    'frontend',
    'backend',
    'JavaScript',
    'React',
    'Next.js',
    'Node.js',
    'Python',
    'dicas de programação',
    'tutoriais de código',
    'smartphones',
    'Android',
    'iOS',
    'iPhone',
    'Samsung',
    'apps de celular',
    'reviews de tecnologia',
    'comparativo de celulares',
    'notebooks',
    'ultrabooks',
    'PC gamer',
    'hardware',
    'componentes de computador',
    'Windows',
    'Linux',
    'macOS',
    'sistemas operacionais',
    'segurança digital',
    'privacidade na internet',
    'nuvem',
    'cloud computing',
    '5G',
    'metaverso',
    'blockchain',
    'criptomoedas',
    'startups de tecnologia',
    'carreiras em tecnologia',
    'tecnologia no Brasil',
    'eventos de tecnologia',
    'tendências tecnológicas',
    'automação',
    'dispositivos inteligentes',
    'gadgets',
    'wearables',
    'tecnologia sustentável',
    'realidade aumentada',
    'realidade virtual',
    'tecnologia no dia a dia'
  ]